### ISSUE TITLE
Make styled-jsx import idempotent

### ISSUE THREAD

**Issue by timneutkens** [zeit/styled-jsx#122]
The import should only be included once.
https://github.com/zeit/next.js/pull/968

**Comment by giuseppeg** [comment]
This is all about babel configuration right? 
Also it may be a styled-jsx-postcss AND Next.js specific issue. 

In styled-jsx-postcss I explicitly decided to extend styled-jsx to make it easy to use/setup. I get the problem but I am not sure if it makes sense to change that because of Next.js – I don't want to make setup harder for people that don't use Next.

**Comment by giuseppeg** [comment]
fwiw I will fix this in styled-jsx-postcss as follow giuseppeg/styled-jsx-postcss/issues/10

**Comment by timneutkens** [comment]
Great 👍
