### ISSUE TITLE
Add :host pseudo-class support

### ISSUE THREAD

**Issue by giuseppeg** [zeit/styled-jsx#13]
In Shadow DOM `:host` selects the element hosting a shadow tree. 
Similarly the legacy scoped styles spec added a [`:scope` pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope).

Maybe someone would ❤️ the idea of being able to use this selector and we/you can add support for it.

[Further reading](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#host).

**Comment by rauchg** [comment]
Yeah this is interesting. I like this more than the flat CSS stuff as it's non-standard (#8)

**Comment by rauchg** [comment]
@giuseppeg another alternative I'm considering, based on my experience so far, it's to contemplate the parent element in the selectors:

```js
<div>
  <style jsx>{`
    div { /* this would work */
      color: red;
    }
  `}</style>
</div>
```

Would love to hear your thoughts

**Comment by rauchg** [comment]
But in that case `:scope` could be better indeed

**Comment by giuseppeg** [comment]
I imagine that there are some benefits in using `:host` which by the way I prefer over the legacy `:scope`. 

If you don't make a distrinction between host and inner divs you might need to use weird hacks when you want to target only the wrapping div. 

For example setting a border on the component would be tricky. A solution could be to add a class e.g. `root` to the parent div to work around this issue but chances are that other styles will apply:

```jsx
<div className="root"> {/* this gets both styles */}
  <style jsx>{`
    .root { border: 1px solid red; }
    div { color: red; }
  `}</style>
</div>
```

**Comment by rauchg** [comment]
Yeah right now on zeit.co we use the class trick. I think I'm going to add support for both. Thanks for the feedback @giuseppeg

**Comment by rauchg** [comment]
So, I decided against `:host` because it could be potentially confusing if you're actually wrapping the rendered JSX in an real web component. Plus , `:host` targets an element that's not _declared_ (the root), so the semantics would have been changed.

I think ultimately the most correct analogy would be `:scope`, but then again this is not _exactly_ like `<style scoped>`, since we only inject styles once per element and they apply to all components.

To conclude, I decided to _also_ give the user the ability to target the root. This is based on our experience using this approach, and me testing the alternative recently.

More:
https://github.com/zeit/styled-jsx/commit/8769645c64d02b747ea04e6234e990bb0f34e951

**Comment by rauchg** [comment]
On the other hand, I also think `:host-content` could give us `>>` without us having to invent something new. So I will play around with that

**Comment by giuseppeg** [comment]
As I see it this react component:
```jsx
<div>
  <style jsx>
    :host { border: 1px solid red }
    span { color: red }
  </style>
  <span>hi</span>      
 {this.props.children}
</div>
```
is equivalent to:
```html
<div>
   #shadow-root
      <style>
        :host { border: 1px solid red }
        span { color: red }
      </style>
      <span>hi</span>
      <content></content>
</div>
```

**Comment by giuseppeg** [comment]
`:host-content` is for components authors (3rd parties) to define variations based on what is the container. So it can't be used by the consumers of the component to override styles. 

I left [a comment](https://github.com/zeit/styled-jsx/issues/26#issuecomment-265715464) on #26 with two ways of controlling styles in web components – this idea could work for us as well.

**Comment by rauchg** [comment]
Yeah I just realized that. I think slots add some complexity.

I'm thinking now about going back to `>>>` as a way of bypassing prefixing:

```js
<div>
  <ComponentWithParagraphs />
  <style jsx>{`
      div >>> p {
        color: red
      }
  `}</style>
</div>
```

and then explicit global styles:

```js
<div>
  <ComponentWithParagraphs />
  <style jsx={{ global: true }}>{`
      body {
        background: blue
      }
  `}</style>
</div>
```

**Comment by rauchg** [comment]
The second one I'm not 100% sure this module should handle.

**Comment by rauchg** [comment]
From the perspective of static analysis, I think we're also better off with:

```
<div>
  <ComponentWithParagraphs />
  <style jsx global>{`
    body {
      background: blue
    }
  `}</style>
</div>
```

**Comment by giuseppeg** [comment]
Closing this since it may never going to happen (we have a way to select the root now). @rauchg feel free to reopen if you want `:host` implemented at some point.

**Comment by treshugart** [comment]
I just wanted to give `:host` a +1 in case it matters :). It'd be interesting to see closer alignment to shadow DOM, particularly because I really like the idea of pairing this library with shadow DOM someday.

For example, imagine if I could get native shadow DOM behaviour for most of what I write, but have this as a build step that gives me useful things like global styles (maybe finding a way to apply it to all shadow roots, too). Being able to use native shadow DOM (I've no idea how this would look yet) would offload a lot of processing while adding very useful features on top of it.
