### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by giuseppeg** [zeit/styled-jsx#135]
~~Currently we use [xo](https://github.com/sindresorhus/xo) to lint our code.
We should replace it with [standard.js](https://github.com/feross/standard)~~

Let's just add Prettier. See https://github.com/zeit/now-cli/blob/master/package.json#L39-L52

**Comment by nkzawa** [comment]
I wonder if we can just format by `https://github.com/jlongster/prettier` instead. @rauchg

**Comment by giuseppeg** [comment]
We can have "prettier" fixtures but we still need a linter for the library code

**Comment by giuseppeg** [comment]
oh wait I thought prettier was only for JSX, awesome!

**Comment by rauchg** [comment]
prettier + linting rules for mistakes / warnings

**Comment by nikvm** [comment]
I started experimenting with this.

My starting point was to lint using [`eslint-config-standard`](https://github.com/feross/eslint-config-standard) as base and resetting styling rules with [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier). The idea was then to auto-fix styling on a [pre-commit hook](https://github.com/prettier/prettier#pre-commit-hook-for-changed-files) and only lint for common mistakes. This way a dev isn't bothered at all with errors like `there should be a space at line 22 column 68`. Also vanilla `eslint` makes it easy to use editor plugins for real time feedback.

__The problem__: I noticed `prettier` adds semicolons to the output which might not be configurable any time soon (discussion [here](https://github.com/prettier/prettier/issues/736)). There is a workaround for this, like piping `prettier`'s output into `standard --fix` (There is a [package](https://github.com/dtinth/prettier-standard-formatter) for that). In this case code gets formatted once using `prettier`'s advanced algorithm and then again using `standard --fix`. Which&mdash;due to different styling rules&mdash;does more than just removing semicolons. In my opinion this gets more complicated than it needs to be.

This might not be a big problem. But before I continue I wanted to check what the general consent is or rather what the expected developer experience is concerning linting and (auto-fixing) code style.

My suggestion is to use `prettier` as is or just use `standard` by itself (which again leaves a dev with styling errors, also fixable by  using `--fix` somewhere in the chain).

📓 You may experiment with the changes [here](https://github.com/nikvm/styled-jsx/tree/feature/pretty-standard). After cloning run `yarn install` followed by `npm run lint` and `npm run prettier` or `npm run prettier-standard`. Diff the output.

cc @giuseppeg @rauchg

**Comment by nikvm** [comment]
I just realized me rambling along last night and maybe not making any sense. 🙉 

Anyways I submitted a [PR](https://github.com/zeit/styled-jsx/pull/145) which I believe is a good starting point for further discussion. :octocat:

**Comment by giuseppeg** [comment]
@nikvm cool! Maybe we can just use prettier-eslint + omit semicolons? 
Do we need other plugins from standard.js? It'd be nice to keep the setup minimal and unopinionated – the semicolons is the only exception I'd allow.

**Comment by nikvm** [comment]
@giuseppeg I continued the discussion in the [PR thread](https://github.com/zeit/styled-jsx/pull/145).
