### ISSUE TITLE
Allow expressions that create selectors

### ISSUE THREAD

**Issue by tuckerconnelly** [zeit/styled-jsx#162]
I tried creating an expression like:

```js
const makeResponsiveStyle = selector => `
  ${selector} {
    ...
  }

  @media (min-width: 800) {
    ${selector} {
      ..
    }
  }
`
```

And then using it like

```js
<style jsx>{`
  ${makeResponsiveStyle('.myComponent')
`}</style>
```

But didn't work :( Seemed to strip out everything the function created.

**Comment by giuseppeg** [comment]
In your example `${makeResponsiveStyle('.myComponent')` there a missing close `}`.

Anyway this can't work because only styles defined within a JSX element are processed. 
When processing, expressions are replaced with a placeholders and the CSS string feed to the css processor which takes care of scoping selectors.

```jsx
<div>
 <style jsx>{`div { color: ${myColor} }`}</style>
</div>
```

* We grab `div { color: ${myColor} }`
* replace `${myColor}` with a placeholder so now you have `div { color: __styledjsxexpression_0_ }` which can be parsed by stylis (the css processor).
* Stylis scopes the selectors so the original string becomes `div[data-jsx="SomeUniqueId"] { color: __styledjsxexpression_0_ }`
* At this point we can restore the expressions `div[data-jsx="SomeUniqueId"] { color: ${myColor} }`

Maybe you can use a constant (expression) for the media query?

```jsx
<div>
 <style jsx>{`
    div { color: ${myColor} }
    @media ${screenMedium} {
       div { color: ${myOtherColor} }
    }
 `}</style>
</div>
```

**Comment by tuckerconnelly** [comment]
It works! Need the `()` around the media query though, or stylis adds another `@media` for some reason.

```
          @media (${breakpoints.sm}) {
            .myComponent {
              background-color: pink;
            }
          }
```
