### ISSUE TITLE
Add hash to class instead of adding data-jsx attribute

### ISSUE THREAD

**Issue by pietrasiak** [zeit/styled-jsx#179]
Is it possible to make classes names modified instead of adding data-jsx attribute to them and to css selectors?

Let's say I've got class `header` - while `styled-jsx` css will apply only to this class, and will not cause conflicts, some external css that has `.header` css might modify my element.

**Comment by giuseppeg** [comment]
@pietrasiak thanks for bringing this up - it might indeed be an issue.
Unfortunately though rewriting classNames won't work for element and attribute selectors. This issue is similar to #27 
Also in some (rare) people may use original selectors in JavaScript e.g. imagine you get the `ref` to an element and then select something with `ref.querySelector('.thing')`
