### ISSUE TITLE
Jetbrains IDEs syntax support

### ISSUE THREAD

**Issue by davegomez** [zeit/styled-jsx#186]
I usually use Webstorm for React projects thanks to it's great JSX syntax support and the IDE tooling so It would be great if we have syntax support for Styled-JSX in the Jetbrain's IDEs.

**Comment by benjaminjackman** [comment]
One trick is to add language injection comments before the literal.

Something like this
'''
//language=CSS
' 
  h1 { color:red }
'
'''
See more here
https://www.jetbrains.com/help/idea/2017.1/using-language-injections.html#injection_comments

You can also add before and after to the comment to tell the IDE to pretend that the code in the literal is surrounded by wrapping code you specify in the before and after blocks.

Finally sometimes i use SCSS if interpolating variables in the template string since that fools the IDE into accepting the $ as legal which they aren't in vanilla CSS.

**Comment by davegomez** [comment]
Awesome, this works!

```
    <style jsx>{{ /*language=SCSS*/ } `
      .container {
        margin: 0 auto;
        width: 880px
      }
    `}</style>
```

**Comment by giuseppeg** [comment]
@davegomez @benjaminjackman would you like add that to the README?

**Comment by RusinovAnton** [comment]
Is it still possible to have syntax highlight without adding injection comments? Not everyone on our team using Idea editor. Isn't is possible to have plugin for this?

**Comment by slpixe** [comment]
I agree it would be good to have this as a plugin for IDEA, as most the other editors have plugins/extensions for styled-jsx

**Comment by alextiley** [comment]
For those still interested in the original request, installing the Styled Components jetbrains plugin also seems to work for styled-jsx. 

https://plugins.jetbrains.com/plugin/9997-styled-components

**Comment by nhooyr** [comment]
@alextiley afaik it does not work for styled JSX. At least not for me. See

<img width="992" alt="Screen Shot 2019-05-11 at 12 14 07 PM" src="https://user-images.githubusercontent.com/10180857/57572300-480d1500-73e6-11e9-8830-c8e67c79fa9e.png">

**Comment by denofevil** [comment]
Please follow styled-components/webstorm-styled-components#77, I think it will be ready this week.
