### ISSUE TITLE
Move from ava to Jest

### ISSUE THREAD

**Issue by giuseppeg** [zeit/styled-jsx#195]
It would be nice to replace ava with Jest since most of our tests are snapshots after all.
See test/fixtures/

**Comment by tdeschryver** [comment]
If its ok I wanna try to take this one.
I've set it up for one test at the moment and would like have some feedback before I continue.
You can take a look @ [https://github.com/zeit/styled-jsx/compare/master...tdeschryver:master](https://github.com/zeit/styled-jsx/compare/master...tdeschryver:master)

**Comment by giuseppeg** [comment]
@tdeschryver awesome thanks! Yeah what you've got looks good to me. 

Maybe we won't need `__tests__/helpers/_read.js` anymore. 
We can also avoid having a separate file per test and just stick with the current few files approach.

Are you at react conf by any chance?

**Comment by giuseppeg** [comment]
fwiw I think that avajs 0.18 or 0.19 supports snapshot testing, maybe we can just upgrade ava and replace our `.out.js` fixtures with snapshots?

**Comment by tdeschryver** [comment]
@giuseppeg 
- my bad, I will delete `__tests__/helpers/_read.js`
- I will keep the current few file approach, the reason why I placed them in a different file was to have different snapshot files instead of one file with all the snapshots.
- I will not be attending react conf
- You're right snapshots are now integrated in avajs (they are using the jest-snaphot lib underneath), so lets stick with avajs?

**Comment by giuseppeg** [comment]
@tdeschryver yep let's stick with avajs :) 

> I will keep the current few file approach, the reason why I placed them in a different file was to have different snapshot files instead of one file with all the snapshots.

fair point although it is more practical to work on a single file and add tests as we go
