### ISSUE TITLE
Target styles of children components

### ISSUE THREAD

**Issue by Tomekmularczyk** [zeit/styled-jsx#197]
Hey I started to use styled-jsx with React-Boostrap and I'm having some troubles styling components.

I want to add/override some styles of `.navbar-header` class but code below doesnt work:

![zrzut ekranu 2017-05-18 o 13 43 58](https://cloud.githubusercontent.com/assets/12544704/26200767/12dea362-3bd0-11e7-8fc6-986501028880.png)

Even if I add custom class to Boostrap component styles doesn't apply either:

![zrzut ekranu 2017-05-18 o 13 46 13](https://cloud.githubusercontent.com/assets/12544704/26200841/797124e2-3bd0-11e7-8723-0d02608bec77.png)

The only solution I came up with is adding global styling, but this seems (to me at least) wrong.

![zrzut ekranu 2017-05-18 o 13 48 34](https://cloud.githubusercontent.com/assets/12544704/26200901/c7132ae2-3bd0-11e7-8872-8f17badc32e8.png)

Is there something I do wrong, or this is how it should be in a first place?

P.S I couldn't paste code with proper formatting and I made screenshots.

REPO: https://github.com/Tomekmularczyk/styled-jsx-test

**Comment by giuseppeg** [comment]
did you try to set the class via the `className` attribute? in js `class` is a reserved word

**Comment by Tomekmularczyk** [comment]
@giuseppeg I use `babel-plugin-react-html-attrs`

**Comment by giuseppeg** [comment]
fair enough but does the element get the class?

**Comment by Tomekmularczyk** [comment]
@giuseppeg jest it does.

**Comment by giuseppeg** [comment]
@Tomekmularczyk can you put together a test repo?

**Comment by Tomekmularczyk** [comment]
@giuseppeg I will do that later.

**Comment by Tomekmularczyk** [comment]
@giuseppeg I have created test repository. I've added link to my original question above.

**Comment by giuseppeg** [comment]
@Tomekmularczyk thanks. Your component doesn't have any `div` [there](https://github.com/Tomekmularczyk/styled-jsx-test/blob/master/src/App/NavBar.jsx#L31).

Here's what you could do:

```jsx
// in NavBar.jsx
import uuid from 'uuid'

const uniqueClass = uuid()

export default (props) => (
  <Navbar class="NavBar">
    <Navbar.Header class={uniqueClass} />
    <style jsx>{`
      global(.${uniqueClass}) {
        color: red !important;
        background-color: red !important;
        padding: 100px !important;
      }
    `}</style>
  </Navbar>
)

**Comment by Tomekmularczyk** [comment]
@giuseppeg somehow I couldn't get this working the first time. But is it possible to target nested elements/classess of Components? for example if wanted to target:

`:global(.${uniqueClass}) > a` ?? 

I also found another small issue:

`const bsSM = '@media screen and (min-width: 567px)';`

`${breakpoints.bsMD} {
        :global(.my-class) {
          color: red !important;
          background-color: red !important;
          padding: 100px !important;
        }
      }`

I have updated repo master branch with these two examples.

**Comment by giuseppeg** [comment]
try `:global(.${uniqueClass} > a)` and 

```js
const bsSM = '(min-width: 567px)';
@media screen and ${bsSM} { :global(.my-class) { color: red !important; } }
```

**Comment by Tomekmularczyk** [comment]
second example worked even with `const bsSM = 'screen and (min-width: 768px)';` (which is closer to what I wanted to achieve).

Hovewer first example doesn't work :/

**Comment by pioul** [comment]
Joining the conversation after trying a similar approach to pass a set of classes to a third-party component that's compatible with CSS Modules :)

Thanks for your help on this one @giuseppeg! [This approach](https://github.com/zeit/styled-jsx/issues/197#issuecomment-302430203) seems to have two issues:

1. Valid class names must not start with a digit, but `uuid()` will sometimes start with one. Solved with a small wrapper:
   ```js
   const getUniqueClassName = () => `a${uuid()}`
   ```

2. This is due to SSR. When passing a unique classname through `:global()` like shown above (i.e. when the unique class name is generated outside the `render()` function), the styles are generated server-side and are passed down to the client – from the first server-side import to the client-side, that unique class name remains the same.

   At the same time, once on the client side, importing this same component will lead to another execution of the module's code, hence another run of `uuid()`, hence a different class name being passed to the component. Note that this won't update the `<style>`. The two are out of sync, so that doesn't work.

   Moving the classname generation inside the `render()` method to have the two always in sync doesn't work, it throws `Syntax Error: Expected `classNames` to not come from the closest scope.`

   A solution that feels like a hammer could be to use a store that's shared across server and client (e.g. a Redux store) and generate a bunch of class names on init that will remain the same throughout the app's lifecycle.

   What do you think? If there's a more elegant solution, I'd love to hear it :)

**Comment by giuseppeg** [comment]
@pioul yup good points, mine was just a POF. 
Obviously the unique class name generation should be deterministic.

**Comment by pioul** [comment]
@giuseppeg 👍 now that I think about it, hashing a pre-determined class name instead of using `uuid` should work great!

**Comment by Tomekmularczyk** [comment]
This makes it little cumbersome to work with third-party components and writing `:global` all over the place...

![zrzut ekranu 2017-05-19 o 14 32 09](https://cloud.githubusercontent.com/assets/12544704/26247883/2d6a27e4-3ca0-11e7-9d6d-949ab12d74a5.png)

**Comment by pioul** [comment]
Agreed, a way to access the generated class names at run time would be great, e.g.

```js
<ThirdPartyComponent
  classNames={{
    item: getLocalClassName('.thirdPartyItem'),
    container: getLocalClassName('.thirdPartyContainer'),
  }}
/>
```

In the meantime (unless that's already available?), `<style jsx global>` can help remove some of the noise.

**Comment by giuseppeg** [comment]
> This makes it little cumbersome to work with third-party components and writing :global all over the place

as @pioul you can use `<style jsx global>`

> hashing a pre-determined class name instead of using uuid should work great!

Hashing won't make it unique, if you hash it in another file for different purposes the hash would still be the same and you get a conflict.

**Comment by pioul** [comment]
Yeah of course, a unique string has to be included; for my use-case, using the component's name as a prefix will work great. Out of curiosity @giuseppeg, do you know if the team has discussed a way to reference generated class names at run time? I could see this use-case being pretty common for styling third-party components, and having the library offer a way to do it would make it way easier; I'm happy to open a separate issue for that if that's helpful!

**Comment by Tomekmularczyk** [comment]
Using third-party components makes my component styles look over-complicated and messy to the point its unbearable...

![zrzut ekranu 2017-05-21 o 19 06 10](https://cloud.githubusercontent.com/assets/12544704/26285878/a80827a8-3e58-11e7-8e5e-72b364d14880.png)


Would it be considered wrong (for reason like performance etc.) if I used this library like below for every component?

![zrzut ekranu 2017-05-21 o 19 11 11](https://cloud.githubusercontent.com/assets/12544704/26285920/4d7ad852-3e59-11e7-88c9-c72b1029a80b.png)


I really like the idea of keeping styles in one file where the component is.

**Comment by giuseppeg** [comment]
@Tomekmularczyk if I am not mistaken global styles can be in separate files as components 

```js
// somestyles.js
export default () => <style jsx global>{`
  /* ... */
`}</style>

// imported as a component

import SomeStyles from './somestyles'

export default ({children}) => (
   <SomeStyles />
  <div>
      {children}
  </div>
)
```

or in the same file:

```js
const styles = <style jsx global>{`
  /* ... */
`}</style>


export default ({children}) => (
   {styles}
  <div>
      {children}
  </div>
)
```

Anyway from the next release of styled-jsx you will be able to put your styles in separate files (even scoped styles) https://github.com/zeit/styled-jsx#keeping-css-in-separate-files

**Comment by Tomekmularczyk** [comment]
@giuseppeg I actually very much like to keep styles in the same file. My question was: would it be wrong to use only global styles (`<style jsx global>...</style>`)? That way I could give class to the root tag and use it as a reference to that component (and avoid using `:global` at all).

**Comment by giuseppeg** [comment]
@Tomekmularczyk but the you lose the most cool feature of styled-jsx that is scoped styles :)

**Comment by Tomekmularczyk** [comment]
@giuseppeg When component is really small and doesn't contain other components then it's great. But when I want to add some styles to children components - but only within context of this component - like: make it disappear on breakpoint, then its hard to target this component and you often have to do something like `:global(.FooterSection) :global(.FullList)` like in a example above. So I would prefer something cleaner like with scss above.

**Comment by mattfysh** [comment]
Began using styled-jsx a few hours ago and I've just come across this same issue... also noticed a lot of projects referencing this repo and noting the lack of a non-global solution is preventing them from migrating to styled-jsx. Are there any plans to work on this?

**Comment by giuseppeg** [comment]
@mattfysh would something like this help https://github.com/zeit/styled-jsx/issues/209 ?

**Comment by mattfysh** [comment]
Getting there, imho - it's still more of a workaround than a solution. Take this example for instance:

```jsx
// Component.js
export default ({ className }) => <div className={className}>foo</div>

// Home.js
<Component className="bar" />
<style jsx>{`
  .bar { color: red }
`}</style>
```

My thought process as to why this should Just Work™ out of the box, is as follows:
- I see a selector targeting an element
- I know that to create isolated scope, a unique class name will be generated and applied to the targeted element
- after application, the class name will be passed into the component and applied to the `<div>`
- the flushed styles will also contain the generated & unique class name, applying the correct styling

**I think the biggest assumption I'm making here is around the use of a unique class name to achieve isolation, a la CSS Modules.**

The reason why this isn't working in styled-jsx is due to the use of the data-jsx attribute generated per component, since the div lives in another component there will not be a match between the data-jsx ID created in Home.js, and the one created in Component.js

**Comment by giuseppeg** [comment]
> The reason why this isn't working in styled-jsx is due to the use of the data-jsx attribute generated per component, since the div lives in another component there will not be a match between the data-jsx ID created in Home.js, and the one created in Component.js

Correct. #27 might make what you described possible.

**Comment by giuseppeg** [comment]
See https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent for a solution
