### ISSUE TITLE
when using components library with styled-jsx it must be a peer dependency

### ISSUE THREAD

**Issue by sidorares** [zeit/styled-jsx#225]
Issue: if I ship styled-jsx components library with styled-jsx as it's own runtime dependency server side styles silently generate no results. 

Cause: on a consumer side I also have local styled-jsx styles. For runtime style updates both local components and components from library work ok but server-side `flush()` only [tracks local copy of components](https://github.com/zeit/styled-jsx/blob/57d00db74788166d8fc4631002a53386132c1ef7/src/style.js#L4)

Would be good to detect this somehow or at least mention in documentation.

**Comment by giuseppeg** [comment]
Do you mean that if they transpile the library they should use styled-jsx only as `devDependencies` to build it before releasing? If so yes, but I don't if there is anything that we can do to enforce that.

**Comment by sidorares** [comment]
> Do you mean that if they transpile the library they should use styled-jsx only as devDependencies to build it before releasing?

yes. Potentially we could have (maybe only in dev mode) flush() to raise some (global) flags so when second instance is loaded it would warn

**Comment by arunoda** [comment]
Is is possible to keep components globally. In the server, inside the `global` object and in the client inside the `window` object.
With that, this will fix problems like this.

**Comment by ernestofreyreg** [comment]
I tried @arunoda's suggestion by simply adding `global.` on the `components` variable and it works. Can we have a final solution here? It would help a lot to make styled-jsx a good choice for component libraries.

**Comment by ernestofreyreg** [comment]
After some tests, I found that you might not actually need to do nothing on the `styled-jsx` part. 

If you are creating a component library with `styled-jsx` you DO need to put `react` and `styled-jsx` on the **perDependencies** section. AND need to specify different babel settings for dev and prod environments like:

```
{
  "env": {
    "production": {
      "presets": ["es2015", "react", "stage-1"]
    },
    "development": {
      "presets": ["es2015", "react", "stage-1"],
      "plugins": ["styled-jsx/babel"]
    }
  }
}
```
This will allow you to test your styles on dev and don't try to include references to `style-jsx` on the built version, resulting on simple **style** components with a prop jsx=true and the actual css content.

**Comment by Huvik** [comment]
So what is currently best solution to use? And is there plan for the future?

**Comment by timneutkens** [comment]
Basically this can be fixed once we support transpiling modules 👍

**Comment by fgascon** [comment]
I think the root problem here is that the `StyleSheetRegistry` is instanciated as a singleton in [style.js](https://github.com/zeit/styled-jsx/blob/5213cee0e3aa5f50f61b4f9dfcdd6deb78c1b972/src/style.js#L4) in v2. There is the same problem of global singleton in v1 as @sidorares pointed out. The user of the styled-jsx library should have the choice over how and when to instanciate it. For example, someone might want for SSR the create one per request instead of just using a global one. We could have a provider component pass the styleSheetRegistry to the Style components via context.

Using `global` and `window` would fix the problem, but I don't think introducing globals is a good thing. It might not play nice with other libraries and it might not work with certain use cases.

**Comment by ifyio** [comment]
I'm creating a component library that uses `styled-jsx` for styling and realised that no library styles are generated server-side when the library is consumed. I may me misunderstanding things but the earlier comments made by @giuseppeg and @sidorares suggests that the problem can somehow be fixed in the interim if `styled-jsx` is used as a `devDependency` when the library is transpiled. The problem, however, is that I don't think I quite understand what this means or how it can even work because regardless of whether `styled-jsx` is a `devDependency` or not, I still get the same problem when the library is consumed. Can someone clarify?

**Comment by giuseppeg** [comment]
@ifyio yeah the idea is that in your component package you have `styled-jsx` as 

* (optional) `devDependencies` to build (transpile) it before releasing 
* `peerDepedencies` so that whoever uses it must install `styled-jsx` to use your component

In your app then you can install the component and it should work just fine.

The reason why you might not want to add `styled-jsx` as `dependencies` in your component package is that otherwise each component will have its own "styles manager" (Stylesheet and StyleSheetRegistry) instead of having a single one for the entire app.

**Comment by ifyio** [comment]
Ok it wasn't working for me because my project was depending on the latest version of `styled-jsx` while `nextjs` was using an earlier version. Once I switched to using the version that `nextjs` was using, it then worked as expected as the consumer of the library is a `nextjs` project.
