### ISSUE TITLE
React Fiber v16.0.0-alpha.13 support

### ISSUE THREAD

**Issue by msand** [zeit/styled-jsx#265]
My pull request https://github.com/zeit/next.js/pull/2570 for Fiber support in next.js fails because of peerinvalid Peer styled-jsx@1.0.8 wants react@15.x.x
Is anyone looking into Fiber compatibility?

**Comment by giuseppeg** [comment]
styled-jsx is not fiber ready and we would need some refactoring to support it.
Would you like to explore a way to make it work?

**Comment by dsifford** [comment]
@giuseppeg I'd love to help with this if still needed.

Curious what the exact issue is for this? I just pulled the repo, installed `react@next` and `react-dom@next` and did nothing else and all the tests pass?

Is there something I'm missing?

**Comment by dsifford** [comment]
@giuseppeg Just took it a step further and dropped my locally updated `styled-jsx` with react and react-dom 16 installed into one of my projects and it appears that everything is working as expected.... I can't get it to _not_ work!

Did the React team fix whatever the problem was on their end perhaps?

**Comment by callumlocke** [comment]
For me, styled-jsx@2.0.0-beta.1 seems to be working perfectly with React@16.0.0 (despite peer deps warning during npm install).

**Comment by giuseppeg** [comment]
@callumlocke yea but it should fail as soon as you try to return an array of react elements I think
