### ISSUE TITLE
Native Shadow DOM support

### ISSUE THREAD

**Issue by treshugart** [zeit/styled-jsx#28]
I'm trying to use this as a way to polyfill CSS encapsulation when working with non-native shadow roots. It works great for that. However, when native support is available, styles aren't applied because the styles are appended to the `<head>`.

It seems from reading the issues and the README, that this is, and will continue to, track close to the shadow DOM specs. If that's the case, would it be worth making this append to the head if no native support is available and simply return the JSX `<style />` tag if it is so that it can just be rendered out?

**Comment by giuseppeg** [comment]
Feature detection would be nice however in order to use native encapsulation you'd need to render your react components into the ShadowDOM which is quite tricky and could possibly result in performance degradation. If you are using ShadowDOM already then my suggestion would be don't use styled-jsx :)

fwiw I was trying to eperiment with rendering into ShadowDOM but never got the time to go beyond [this quick hack](http://codepen.io/giuseppegurgone/pen/xEZVWV?editors=0010) also the spec changed so I need to update myself :)

**Comment by rauchg** [comment]
@treshugart it'd be really cool if we could supplant `/inject`. For example, it could be an option in the babel transformation

**Comment by treshugart** [comment]
@giuseppeg I'm actually using this outside of React in a pure web component library, so no difficulties there.

@rauchg I like the sound of that idea. It covers several use-cases, not just mine. Could use the existing `jsx` attribute an do something like:

```js
<style jsx="shadow-inject" />
```

Slight tangent: The only issue I see from here, you can't do something like this:

```js
const Style = ({ css }) => <style jsx="shadow-inject">{css}</style>;
```

And abstract that away separate from the JSX that is used to render the component. I guess that's not too big a deal, but it would be pretty neat if it's possible.

**Comment by rauchg** [comment]
Yeah I've thought about it. It should technically be possible if it's all static :D But that's where the webpack / babel boundary for module resolution might make it difficult

**Comment by giuseppeg** [comment]
@treshugart hi, I am not sure if this is doable since we support dynamic, external styles and fragments:

```jsx
<React.Fragment>
   <img src={props.src} alt>
   <style jsx>{`img { display: block }`}</style>
</React.Fragment>
```

**Comment by activenode** [comment]
@giuseppeg 
Can you elaborate the exact issue/downside with that?

I was looking into that and a pseudo solution (pseudo in a sense of not knowing all the technical details of styled-jsx) I would think of this:

```
import { createClass } from '@zeit/styled-jsx';

const { className, styleTag } = createClass`
color: red:
`
```

whereas the `className` would be a hashed e.g. `.jsx-123` and the `styleTag` would return a string containing the style tag (just as if it was rendered serverside).

**Comment by giuseppeg** [comment]
@activenode hi! The solution you described is already implemented - you can search the README for the `resolve` tag.

The issue with https://github.com/zeit/styled-jsx/issues/28#issuecomment-449555432 specifically is that in the browser there is no such thing as fragment elements so we couldn't convert that example to (S)DOM.

**Comment by activenode** [comment]
That is confusing to me since when I am using the `resolve` tag then it is putting the `<style>` tag to the `<head>` of the document!

This means that it is **effectively useless** combined with shadow dom.

I found a solution that looks like this but it seems to be dirty:

```
const { className, styles } = css.resolve`
  color: green;
`;

const MyStyleTag = <style>{styles.props.children}</style>;

const MyComponentInsideShadowDom = () => {
    return <>
       <span className={className}>foobar</span>
       <MyStyleTag />
    </>
}
```

What is your opinion on this?
