### ISSUE TITLE
Variables from closest scope do not process before plugins

### ISSUE THREAD

**Issue by khrome83** [zeit/styled-jsx#333]
As you can see from here - https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/3

There is currently a issue where variables used in closest scope are not handled before the styles are sent to the plugins for processing. 

I filed the issue with the PostCSS plugin, incase the issue is with that repo. But it could be the order of operations with how stuff where the PostCSS plugin should be receiving cleansed data. Let me know if I should move the issue here.

**Comment by giuseppeg** [comment]
Interpolations (variables) are resolved at render time and plugins receive a css string with placeholders instead of variables since plugins or our lib to scope selectors doesn’t understand interpolations. What you need to do is modify the postcss plugin to replace these placeholders with something that postcss can parse, run postcss in the resulting string and then restore the original placeholders. Please read the plugins section in the readme of this repo and look at the implementation of styled-jsx-plugin-postcss
