### ISSUE TITLE
resolveScopedStyles include in API

### ISSUE THREAD

**Issue by pungggi** [zeit/styled-jsx#379]
Hi @giuseppeg 

what do you think about embed the resolveScopedStyles function from https://github.com/zeit/styled-jsx/issues/273 in the library.
So users can import it when needed?

Like

`import {resolveScopedStyles} from 'styled-jsx'`

?

**Comment by giuseppeg** [comment]
@pungggi it is a few lines utility that can be implemented by the users. I don't think that it is necessary to include it in the library.

**Comment by jadengore** [comment]
@giuseppeg I think this could be really useful to be added as a template tag function, something like `thirdPartyCss`.

**Comment by Vadorequest** [comment]
@giuseppeg I disagree, when you find online examples using `resolveScopedStyles` but have no idea where it came and relentlessly try to import it like `import {resolveScopedStyles} from 'styled-jsx'`, but because there is no export at styled-jsx you end up thinking it's not correctly installed  and reinstall all node packages, to finally figure out it's non-provided.

**Comment by giuseppeg** [comment]
In v3 we are adding the following syntax:

```css
const { className, styles } = css.resolve`div { color: red }`
```

to do the same thing
