### ISSUE TITLE
An example code on docs causes Next.js to crash.

### ISSUE THREAD

**Issue by AtaruOhto** [zeit/styled-jsx#545]
#### Do you want to request a *feature* or report a *bug*?

:bug: (Probably)

#### What is the current behavior?

using styled-jsx causes Next.js to crash.

<img width="1326" alt="localhost_3000" src="https://user-images.githubusercontent.com/3450879/51599353-b8c91800-1f42-11e9-8918-c8f8d05e0231.png">

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Here is the Next.js project to reproduce.

[next.zip](https://github.com/zeit/styled-jsx/files/2786693/next.zip)

```
1: yarn
2: yarn dev
3: access http://localhost:3000
```

and the following screen will be shown.

<img width="1326" alt="localhost_3000" src="https://user-images.githubusercontent.com/3450879/51599353-b8c91800-1f42-11e9-8918-c8f8d05e0231.png">

#### What is the expected behavior?

styled-jsx gives correct styles to Next.js and not cause crash.

#### Environment (include versions)

* OS: 10.13.6
* Node v8.11.1
* styled-jsx: 3.2.0
* Next.js: 7.0.2

#### Did this work in previous versions?

Yes. I confirmed that styled-jsx and Next.js worked fine in TypeScript project before.

**Comment by ijjk** [comment]
@AtaruOhto, since `styled-jsx` is included in Next.js forcing the version in this way seems to break it. You can specify a different `styled-jsx` version from what Next.js sets by either using the [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) field for `yarn` or [npm-shrinkwrap](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) for `npm`

I reattached your [next.zip](https://github.com/zeit/styled-jsx/files/2790567/next.zip) reproduction showing an example using the `resolutions` field with yarn

**Comment by AtaruOhto** [comment]
@ijjk 

Thank you very much. 
I appreciate your quick and kind answer.

> styled-jsx is included in Next.js forcing the version in this way seems to break it. 

I'm so sorry to trouble you. I assumed that I should bundle styled-jsx manually when using "styled-jsx" with Next.js. I should have read Next.js document more carefully.

I 'm using Next.js in production in another project and like it very much. 
Thank you :)

I'll close the issue.

**Comment by activenode** [comment]
The problem is: What to do when using styled-jsx in a project WITHOUT `next` ?
