### ISSUE TITLE
[feature request] `useStyle` hook like API will be possible, is on roadmap ?

### ISSUE THREAD

**Issue by bySabi** [zeit/styled-jsx#549]
I don't know for sure if a `useStyle` hook could be implemented or is desirable?.
For Example: https://github.com/andywer/react-usestyles

Any insight on this?

**Comment by giuseppeg** [comment]
styled-jsx is mostly a build time tool. There is some runtime but scoping happens at build time - mostly (partially exception for dynamic styles.

I thought of something like this https://twitter.com/giuseppegurgone/status/1059009092709167104
and probably a babel plugin could precompile these and rewrite JSX to include the scoped class name instead of the hook returning a custom `createElement` that adds the scoped class name at runtime.

TBH though I think it is not worth adding so much more features to the library. My hook idea could be implemented as a separate library.
