### ISSUE TITLE
Styled JSX not working on JSX in variable

### ISSUE THREAD

**Issue by zeckdude** [zeit/styled-jsx#607]
#23 ## Do you want to request a *feature* or report a *bug*?

report a bug

#### What is the current behavior?

When a render function is using a variable to conditionally show JSX, it is not respecting the style rules.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

You can see a demo here: https://codesandbox.io/s/styled-jsx-example-e6tf6

I am using a variable to conditionally show different JSX and it isn't using the styling that is defined in its parent function. How can I make that work?

```js
import React from 'react'

function StyledJsxTest({ isLoggedIn, areButtonsVisible }) {
  function renderButtons() {
    const buttons = isLoggedIn ? (
      <a className="button" href="/dashboard">Dashboard</a>
    ) : (
      <>
        <a className="button" href="/signIn">Log In</a>
      </>
    )

    return (
      <div>
        <div>
          <a className="button" href="/dashboard">Test</a>
          {buttons}
        </div>
        <style jsx>{`
          .button {
            background-color: blue;
            color: white;
            padding: 20px;
            margin: 10px;
          }
        `}
        </style>
      </div>
    )
  }

  return (
    <div>
      <h1>This is a headline</h1>
      {renderButtons()}
    </div>
  )
}

export default StyledJsxTest
```

The buttons in this chunk of code are not getting the `. button` rule. How can i get those to work?

```js
const buttons = isLoggedIn ? (
      <a className="button" href="/dashboard">Dashboard</a>
    ) : (
      <>
        <a className="button" href="/signIn">Log In</a>
      </>
    )
```

#### What is the expected behavior?

It should still style any element with the `.button` class regardless if it is in the returned JSX or in the variable that is being used by the returned JSX.

#### Environment (include versions)

* OS: Mac Catalina
* Browser: Chrome
* styled-jsx (version): 9.1.4

**Comment by giuseppeg** [comment]
styled-jsx styles apply only to their siblings and parent element

```
<div>
<button>hi</button>
<style jsx>{`
div { color: red }
button { color: green }
`}</style>
</div>
```

In other cases you have these options https://github.com/zeit/styled-jsx#external-css-and-styles-outside-of-the-component

**Comment by zeckdude** [comment]
So how would I solve my problem then? Can you give me a code sample please? I don’t want to repeat the styling twice.

**Comment by dazulu** [comment]
Hi, @zeckdude. Just from having to do this myself recently, following the link @giuseppeg posted above will lead you to a section titled **"External CSS and styles outside of the component"**, which explains how to go about this in a couple of different ways with `import css from 'styled-jsx/css'`.

This introduces a few changes in how you define CSS in the component. You now use `css.resolve` to define your CSS, instead of defining it in <style jsx> tags. I called that `linkCSS` below. Then in each className, you need to reference `{linkCSS.className}` and where you previously had the <style jsx> tags, replace that with just `{linkCSS.styles}`.

**Good things to know...**
- It is possible to mix this method and use <style jsx> definitions in the same component, targeting other elements that don't need the special treatment.
- When you're defining styles inside `css.resolve`, you must target the HTML Tag name of your element. Only tag names and only one tag.
- The `css.resolve` method enables you to use JS variables inside that CSS, which can be quite powerful.

This is your component with the necessary changes...
```js
import React from "react";
import css from "styled-jsx/css";

const linkCSS = css.resolve`
  a {
    background-color: blue;
    color: white;
    padding: 20px;
    margin: 10px;
  }
`;

function StyledJsxTest({ isLoggedIn, areButtonsVisible }) {
  function renderButtons() {
    const buttons = isLoggedIn ? (
      <a className={linkCSS.className} href="/dashboard">
        Dashboard
      </a>
    ) : (
      <>
        <a className={linkCSS.className} href="/signIn">
          Log In
        </a>
      </>
    );

    return (
      <div>
        <div>
          <a className={linkCSS.className} href="/dashboard">
            Test
          </a>
          {buttons}
        </div>
        {linkCSS.styles}
      </div>
    );
  }

  return (
    <div>
      <h1>This is a headline</h1>
      {renderButtons()}
    </div>
  );
}

export default StyledJsxTest;
```

**Comment by miracle2k** [comment]
I don't think the docs are clear about this. "External CSS and styles outside of the component" doesn't really apply here - the styles are clearly inside the component. It is a super common pattern in React too. While unfortunate that it's not supported, I do think the docs could be more clear about this.
