### ISSUE TITLE
Detect static vs dynamic styles

### ISSUE THREAD

**Issue by aldendaniels** [zeit/styled-jsx#610]
#### Do you want to request a *feature* or report a *bug*?
Request a feature

#### What is the current behavior?
`style-jsx` automatically infers whether a style is static or dynamic, and it's hard to control or predict this behavior.

Because static styles offer better performance than do dynamically generated styles, it's useful to know which behavior is being used. However the rules for static vs dynamic interpolation today are unclear.

For instance:
```typescript
function Square() {
  const size = 100;
  return <div>
    <style jsx>{`
      div {
        width: ${size};
        height: ${size};
      }
    `}></style>
  </div>;
}
``` 

Will this be treated as static, because `size` is a `const` variable, or dynamic because it's defined within the component scope? It's hard to tell.

#### What is the expected behavior?
It's be great if there could be a way to detect which treatment was being used. Better yet would be a way to disallow implicit dynamic styles so that you have have to opt-in to dynamic behavior. 

Thanks in advance for the help! Disclaimer: I'm new to `styled-jsx`.

#### Environment (include versions)

* OS: mac
* Browser: all
* styled-jsx (version): `3.2.4`

#### Did this work in previous versions?
No

**Comment by giuseppeg** [comment]
hi @aldendaniels. Good point! Currently styled-jsx treats any interpolation defined within the component as dynamic, this is to simplify things. Internally styled-jsx uses a cache for the computed dynamic rules which is based on those interpolation values, therefore even though this is a dynamic rule the actual rule will be taken from the cache since `size` doesn't change.

An improvement to this could be to try to evaluate expressions (interpolations) at compile time - I did this for another library of mine https://github.com/giuseppeg/style-sheet/blob/aa125093adcef82ca3bd86b58f5f203ef232a4fa/src/babel.js#L259

Probably though most of the times the current approach is fine. Let me know in case you want to try to implement this improvement otherwise I will close this issue as I don't have time to work on this atm.

**Comment by aldendaniels** [comment]
> Currently styled-jsx treats any interpolation defined within the component as dynamic, this is to simplify things

Gotcha, makes sense.

> Let me know in case you want to try to implement this improvement otherwise I will close this issue as I don't have time to work on this atm.

I've had some issue with dynamic global styles so have avoided those, but otherwise the current behavior works fine for my needs ATM so feel free to close at your discretion. 

Thanks!
