### ISSUE TITLE
Allow for importing styles

### ISSUE THREAD

**Issue by thisbejim** [zeit/styled-jsx#83]
Sometimes styles can be quite long and it makes sense for them to live in a seperate file. For example, if you are using [next.js](https://github.com/zeit/next.js) and you want to put your styles in a `./styles.js` file next to a component (minimal styling just for the example):
```
export default `
  p {
    color: red;
  }
`
```
Then import it:
```
import styles from './styles';

export default () => (
  <div>
    <p>only this paragraph will get the style :)</p>
    <style jsx>{styles}</style>
  </div>
)
```

Will give you the following error: `Module build failed: SyntaxError: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got Identifier`.

**Comment by giuseppeg** [comment]
I believe that external styles could be enabled with a `<link jsx href="path/to/styles.js" />` tag or if we don't care about semantics `<style jsx href="path/to/styles.js" />`.

`path/to/styles.js` should export a styles literal:

```js
export default `
  p { color: red; }
`
```

which we transpile to:

```js
module.exports = {
  css: `p[data-jsx="woot"] { color: red; }`,
  id: 'woot'
}
```

Tbd how to handle the `global` flag.

**Comment by thysultan** [comment]
@giuseppeg stylis does have support for handling sass like `@import` tokens, and passes it to a middleware if provided, you could use this to then import the requested files and return them as a string and the compiler will continue from there.

**Comment by giuseppeg** [comment]
@thysultan interesting... that works only for plain css though right? Now we support expressions within template literals so external styled jsx files should be javascript modules.

**Comment by thysultan** [comment]
@giuseppeg Yes a string so you might do...

```js
var m = new module.constructor();
m._compile('module.exports = fs.readFileSync(filename, 'utf8'), filename);
var str = m.exports;
return str;
```

**Comment by giuseppeg** [comment]
@thysultan the problem is that in styled jsx you can do the following

```jsx
import {primary} from '../theme/colors'

export default `
  p { color: ${primary}; }
`
```

**Comment by thysultan** [comment]
@giuseppeg couldn't you still transpile that will babel and do `m._compile('module.exports = ....` pointing to the content of the exported template literal.

**Comment by giuseppeg** [comment]
do you mean resolve the template literal to static string?

**Comment by thysultan** [comment]
Yes, have babel compile.

```
import {primary} from '../theme/colors'

export default `
  p { color: ${primary}; }
`
```

Then pass that through

```
var m = new module.constructor();
m._compile('module.exports = `'+transpiledFileContent+'`', filename);
var str = m.exports;
```

Now you have a static string like `"p { color: blue; }"` then stylis can replace the import statement with this and parse/compile it. The same can be done for other file types i.e where as `@import "foo.js"` or something like `@import "foo.sjsx"` would import require a babel compile `@import "foo.scss"` or ``@import "foo"`` assumed non js files would not, stylis avoids `@import "file.css"` imports to avoid css syntax conflicts.

**Comment by davibe** [comment]
I have used babel inline-import plugin https://www.npmjs.com/package/babel-plugin-inline-import
and registered it for `.css` file extention. I was able to do the same also using other plugins like https://github.com/gnandretta/babel-plugin-transform-css-import-to-string

Doing that babel automatically inlined my css in js. However, inlining file A in file B any changes in file A will not trigger hot-reloading unless you also change B.

I believe being able to use external files with hot-reloading is needed because
- when styles get too long it's easyer to manage an external file
- syntax hilight: right now only atom can do it. If you use another editor/tool you need to write a css plugin that is able to hilight css-in-js. It also means that you have to do that for every language you can possibly inline (for example i used [markdown-in-js](https://github.com/evilstreak/markdown-js) but there is also sass/less/..), for every editor/tool, you need to add support for hilighting by creating plugins.
- in general it would allow people to use any tools they already use to generate the files they want to inline automatically.

**Comment by giuseppeg** [comment]
@davibe cool indeed using something like babel-plugin-inline-import gets the job done if you don't need constants in your jsx (string interpolation). Hot-reloading is out of the scope of this package.

**Comment by arunoda** [comment]
Guys, I hacked for something like this:

```js
export default class {
  render () {
    return (
      <div>
        <p>test</p>
        <style jsx src="./src-style.css" />
      </div>
    )
  }
}
```

See Implementation: https://github.com/arunoda/styled-jsx/blob/style-src/test/fixtures/src.js

But with this, we can't get hot reload for CSS changes. Which is not something great. So, I gave up on this idea.

**Comment by giuseppeg** [comment]
I believe that if we use js modules like i [suggested above](https://github.com/zeit/styled-jsx/issues/83#issuecomment-274043635) we would also get hot reload.

I am not a big fan of inlining css because potentially it can be used by many components so we would inline it more than once. Also now we support constants so external css file should be js modules imho.

**Comment by sheerun** [comment]
I'd imagine a nice approach would be to support `@import` keyword along `composes`, as so:

```jsx
<div>
  <button>Hello world</button>
  <style jsx>{`
    @import 'bootstrap.css';

    button {
      composes: btn btn-primary;
      font-size: 30px;
    }
  `}</style>
</div>
```

**Comment by sheerun** [comment]
@giuseppeg I've asked babel team for tips how to implement such plugin: https://github.com/babel/babel/issues/5505

**Comment by sheerun** [comment]
It seems changing parser per-file is totally possible:

https://github.com/lightscript/babel-plugin-lightscript/blob/master/src/index.js#L1001

**Comment by giuseppeg** [comment]
@sheerun thanks that's very interesting and useful information!

We are trying to keep CSS (styled-jsx) as standard compliant as possible without introducing custom features. The reason for this choice is that anybody has personal preferences and not necessarily universally wanted sets of custom features that would like to use/have. 

Those imho belong to user land and can be implemented as an extension of styled-jsx in some cases (see [styled-jsx-postcss](https://github.com/giuseppeg/styled-jsx-postcss)). 

In this particular case I would like to avoid to reinvent the CSS Modules composes feature.

**Comment by yn5** [comment]
Any updates on this? Not being able to import styles is a big deal breaker for us, apart from that we'd love to use this library.

**Comment by giuseppeg** [comment]
@yn5 it is wip #148
